### PR TITLE
Fix eventMacro quests

### LINKED ISSUE #3934: Quest missions undefined key
Quest missions has as undefined key sometimes (always?), tested in idRO.
This makes eventMacro and other similar checks fail

43e1a58c220a053e175eb56da0e00bae

### PR DESCRIPTION
**Pull request by Henrybk**
All eventMacro quest conditions relied on packet_mapChange and inventory_ready which either don't work always in xkore 3 (packet_mapChange) or don't work at all in new clientes (inventory_ready), this should fix them all.

Fixes #3934

### CODE REVIEW

File: src/Network/Receive.pm [hunk 1]
```diff
@@ -4737,6 +4739,8 @@ sub quest_all_mission {
 			});
 		}
 	}
+
+	Plugins::callHook('quest_mission');
```
Comment (ya4ept) [inline src/Network/Receive.pm:4743]: I suggest renaming it to "quest_all_mission_end"

File: src/Network/Receive.pm [hunk 2]
```diff
@@ -4906,13 +4910,17 @@ sub quest_update_mission_hunt {
 			goal => $quest_mission->{mob_goal}
 		});
 	}
+	
+	Plugins::callHook('quest_update_mission');
```
Comment (ya4ept) [inline src/Network/Receive.pm:4914]: I suggest renaming it to "quest_update_mission_hunt_end"

File: plugins/eventMacro/eventMacro/Condition/QuestTimeOverdue.pm [hunk 3]
```diff
@@ -6,9 +6,8 @@ use eventMacro::Utilities qw( find_variable );
 
 use base 'eventMacro::Condition';
 
-# Using 'inventory_ready' is not optimal, but it works.
 sub _hooks {
-	['packet_mapChange','inventory_ready','packet/quest_all_list','packet/quest_all_list2','packet/quest_all_list3','packet/quest_all_mission','packet/quest_add','packet/quest_delete','packet/quest_update_mission_hunt','packet/quest_active'];
+	['quest_list','quest_mission','quest_added','quest_update_mission','quest_delete','quest_active'];
```
Comment (ya4ept) [inline plugins/eventMacro/eventMacro/Condition/QuestTimeOverdue.pm:10]: suggest renaming "quest_list" to "quest_all_list_end"

**Review by ya4ept — CHANGES_REQUESTED** [review]

**Comment by ya4ept** [comment]
@Henrybk  Does this fix issue #3804?

**Comment by Henrybk** [comment]
QuestHuntCompleted by definition checks if a specific hunt mission is completed (count == goal), so it requires both quest ID and either mob ID or hunt ID. I could make another condition like QuestHuntCompletedAll which just returns true if all hunt missions of a specific quest are completed.

Both QuestHuntCompleted and QuestInactive were not working correctly so yes it fixes both of those issues also.

**Review by ya4ept — APPROVED** [review]
looks good
